openapi: 3.0.0
info:
  title: My API
  version: 1.0.0

paths:
  /my-resource:
    post:
      summary: Get my resource
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${aws_region}:${data.aws_caller_identity.current.account_id}:function:test-lambda/invocations
        httpMethod: POST
        type: aws_proxy
        contentHandling: CONVERT_TO_TEXT
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
