{
  "openapi": "3.0.0",
  "info": {
    "title": "My API",
    "version": "1.0.0"
  },
  "paths": {
    "/dev-rg-ano-mod": {
      "post": {
        "summary": "Run Inference",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "data": {
                    "type": "object",
                    "properties": {
                      "totalCasinoStakeCentsUsdInWindow": {
                        "type": "object",
                        "additionalProperties": {
                          "type": "number"
                        },
                        "example": {
                          "0": 105,
                          "1": 25.65
                        }
                      },
                      "valueOfDepositsCentsUsdInWindow": {
                        "type": "object",
                        "additionalProperties": {
                          "type": "number"
                        },
                        "example": {
                          "0": 1,
                          "1": 2500.35
                        }
                      }
                    },
                    "required": [
                      "totalCasinoStakeCentsUsdInWindow",
                      "valueOfDepositsCentsUsdInWindow"
                    ]
                  }
                },
                "required": [
                  "data"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "prediction": {
                      "type": "array",
                      "items": {
                        "type": "array",
                        "items": {
                          "type": "integer"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        },

       
      }
    }
  }
}
