
openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
  

paths:
  /my-resource:
    post:
      summary: Get my resource
      
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${aws_region}:558940753150:function:test-lambda/invocations
        httpMethod: POST
        type: aws_proxy
        contentHandling: CONVERT_TO_TEXT
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object

x-amazon-apigateway:
  name: MyAPIGateway
  deployments:
    dev:
      description: Development deployment
    prod:
      description: Production deployment

x-amazon-apigateway-stage:
  dev:
    deployment: dev
    description: Development stage
  prod:
    deployment: prod
    description: Production stage

x-amazon-apigateway:
  name: my-api
  extensions:
    x-amazon-apigateway-api-key-source: HEADER
  deployments:
    - name: dev
      description: Development deployment
  stage:
    - name: dev
      deployment: dev
      description: Development stage

